EE_LIB = julian.a
EE_OBJS = src/battle_subs.o

INCDIR =
CFLAGS = -Os -G0 -Wall
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR =
LDFLAGS =

include Makefile.pref
include Makefile.eeglobal